### PR TITLE
add "鑛"  https://www.moedict.tw/~%E9%91%9B

### PR DESCRIPTION
**Pull request by irvin**
金「鑛」咖啡

### CODE REVIEW

**Comment by mjhsieh** [comment]
http://dict2.variants.moe.edu.tw/variants/rbt/word_attribute.rbt?quote_code=QTAyODczLTAwNA

**Comment by mjhsieh** [comment]
There are two variants: CNS:11-702F and CNS:11-6F5B in 研考會(內政部地政用字), but apparently they mostly shared the same entry in 教育部 data.

**Comment by mjhsieh** [comment]
Ah, you are sending the PR to the wrong place. Please send your PR to the right repository. https://github.com/OpenVanilla/McBopomofo

**Comment by mjhsieh** [comment]
我不知道怎麼會變成這樣，我不記得有從 OV fork 這個 repo, 應該是 github 問題。

**Comment by irvin** [comment]
Github 只要發 PR 就會自動 fork 一份；網址問題我發另一個 P/R 了

**Pull request closed without merging**
